// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expenses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExpensesByUserID = `-- name: CountExpensesByUserID :one
SELECT COUNT(*) FROM expenses
WHERE user_id = $1
  AND ($2::date IS NULL OR date >= $2::date)
  AND ($3::date IS NULL OR date <= $3::date)
  AND ($4::uuid IS NULL OR category_id = $4::uuid)
`

type CountExpensesByUserIDParams struct {
	UserID  pgtype.UUID
	Column2 pgtype.Date
	Column3 pgtype.Date
	Column4 pgtype.UUID
}

func (q *Queries) CountExpensesByUserID(ctx context.Context, arg CountExpensesByUserIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExpensesByUserID,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (user_id, category_id, amount, note, date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, category_id, amount, note, date, created_at, updated_at
`

type CreateExpenseParams struct {
	UserID     pgtype.UUID
	CategoryID pgtype.UUID
	Amount     int64
	Note       pgtype.Text
	Date       pgtype.Date
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Note,
		arg.Date,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Note,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses
WHERE id = $1 AND user_id = $2
`

type DeleteExpenseParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteExpense(ctx context.Context, arg DeleteExpenseParams) error {
	_, err := q.db.Exec(ctx, deleteExpense, arg.ID, arg.UserID)
	return err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT e.id, e.user_id, e.category_id, e.amount, e.note, e.date, e.created_at, e.updated_at, c.name as category_name
FROM expenses e
LEFT JOIN categories c ON e.category_id = c.id
WHERE e.id = $1 AND e.user_id = $2
`

type GetExpenseByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetExpenseByIDRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	CategoryID   pgtype.UUID
	Amount       int64
	Note         pgtype.Text
	Date         pgtype.Date
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	CategoryName pgtype.Text
}

func (q *Queries) GetExpenseByID(ctx context.Context, arg GetExpenseByIDParams) (GetExpenseByIDRow, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, arg.ID, arg.UserID)
	var i GetExpenseByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Note,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
	)
	return i, err
}

const getExpenseSummaryByUserID = `-- name: GetExpenseSummaryByUserID :many
SELECT c.name as category_name, SUM(e.amount) as total_amount
FROM expenses e
LEFT JOIN categories c ON e.category_id = c.id
WHERE e.user_id = $1
  AND ($2::date IS NULL OR e.date >= $2::date)
  AND ($3::date IS NULL OR e.date <= $3::date)
GROUP BY c.name
ORDER BY total_amount DESC
`

type GetExpenseSummaryByUserIDParams struct {
	UserID  pgtype.UUID
	Column2 pgtype.Date
	Column3 pgtype.Date
}

type GetExpenseSummaryByUserIDRow struct {
	CategoryName pgtype.Text
	TotalAmount  int64
}

func (q *Queries) GetExpenseSummaryByUserID(ctx context.Context, arg GetExpenseSummaryByUserIDParams) ([]GetExpenseSummaryByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getExpenseSummaryByUserID, arg.UserID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpenseSummaryByUserIDRow
	for rows.Next() {
		var i GetExpenseSummaryByUserIDRow
		if err := rows.Scan(&i.CategoryName, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpensesByUserID = `-- name: GetExpensesByUserID :many
SELECT e.id, e.user_id, e.category_id, e.amount, e.note, e.date, e.created_at, e.updated_at, c.name as category_name
FROM expenses e
LEFT JOIN categories c ON e.category_id = c.id
WHERE e.user_id = $1
  AND ($2::date IS NULL OR e.date >= $2::date)
  AND ($3::date IS NULL OR e.date <= $3::date)
  AND ($4::uuid IS NULL OR e.category_id = $4::uuid)
ORDER BY e.date DESC
LIMIT $5 OFFSET $6
`

type GetExpensesByUserIDParams struct {
	UserID  pgtype.UUID
	Column2 pgtype.Date
	Column3 pgtype.Date
	Column4 pgtype.UUID
	Limit   int32
	Offset  int32
}

type GetExpensesByUserIDRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	CategoryID   pgtype.UUID
	Amount       int64
	Note         pgtype.Text
	Date         pgtype.Date
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	CategoryName pgtype.Text
}

func (q *Queries) GetExpensesByUserID(ctx context.Context, arg GetExpensesByUserIDParams) ([]GetExpensesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getExpensesByUserID,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpensesByUserIDRow
	for rows.Next() {
		var i GetExpensesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Note,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET category_id = $1, amount = $2, note = $3, date = $4, updated_at = NOW()
WHERE id = $5 AND user_id = $6
RETURNING id, user_id, category_id, amount, note, date, created_at, updated_at
`

type UpdateExpenseParams struct {
	CategoryID pgtype.UUID
	Amount     int64
	Note       pgtype.Text
	Date       pgtype.Date
	ID         pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.CategoryID,
		arg.Amount,
		arg.Note,
		arg.Date,
		arg.ID,
		arg.UserID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Note,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
